language: java
jdk: oraclejdk11
notifications:
  slack:
    on_success: always
addons:
  sonarcloud:
    organization: metaxiii
    token:
      secure: WyUnEuu90bcaUymPA7MkG6jN0YDu+UOjYMHISeWZxRJkfc1dy9M96WD7hzU1RP+bhj9711iNvS/Cf0F1mJbVZsz//4BlLGssJk9zXfXNW2Hv3PyqtjrQi5KrlgE+8tWqBms1B+dcRajULlyUpGOPWlhqHQfcuM5lqk98vnyl8qek7wMqAZxvwmAtj4IHdwkcGEJl62YTZpDv74Umjwxem5U0pA8wQ4dsp2Ji3deq4of6xjnyAkZztjr8MU8m9GabVqv41PqAsRpsKev0vmufWrfXshMTDD5BAjgCOn/i9FYsdokCstkbknwUN4/WqnIjXp/rLRTDrO5SSLjYKLJwZu3g4Nor4fUKZB/S6Y+y9+n252sXt1PxdJ1E4Et2qYcZPodWI5tmC63CYiK9WE79y//HxktOuRRJVmFRXbMZ5No1y5vUHXkC6xyt3qiLFMAXZhetmcKtHtICldizEC1ZqmPMIqrBq6ovhWGan4Du/H9ElEvB8F5YHz0xULU/rsOPyhc7H6riuXwB8ismAPzbB8DV+kmFjkbEOuvKuZjyEMxFtkFhowYzl/RPRKK3JDs2ZdOgq1AxAGuHAYr7jBIJXfvgIDZ7HoRrpHABOrgpwqVQzIZ/hSeO0raleuNsOQtpnTg2gDT6Ln5orT0VcIDeKyydJQ34PvSVq8th8US5sU8=
script:
  - mvn clean install sonar:sonar -Dsonar.projectKey=metaXIII_OC-java-P10
