language: java
jdk: oraclejdk11
notifications:
  slack:
    on_success: always

addons:
  sonarcloud:
    organization: metaxiii
    token:
      secure: Hh9GjvUZ0jbU9x4SWQd8ZEmJ8ZsY67qY3zif5fnKjYYpT7/JwxhProueUOKVQQrqA1vTICA4FikGyNjsJMh/xtv7rMC8vEG3vkNcqRVYLIrowJv7vDaZ0EA13psypi0hXa0UciBwPXjh/oVJvWuQeBHX2mac3Oaz1yb7BMnEWJjrbKU5l0QP23/VsUzKUXudVdCbEIy6ml0927/PMw4mi9BMzalKaed6n3rE+Srz9zmr6glcr8zxW8mb21mq7YmrYNwr0njO0wdNBa2+9RMaRsgR6Cuiwoj3DwDeaczEh8dz7O22ZwsFuMj7sijJNJC8rQ2btRmeauGHlGELI8BoUcQFrbh1MqNteiDhINZesC2QsDJR4ES9qIVF+TZadmE5V/eEwV0v913FgvasEC+n7QiovodTUBPeoD80Fqe0gYczOszjKW/vGD8sXb+eeM0RpSDCssgxFsgVcX+RYphG9pPd9Ey2WbAmhBICD+MXOA6UgRF7AuT6QjVevkOTqlssQRlaQQPl2y2DlnuUiY1Dd0kHRQUInnXvA9LftCr+LDVF6GaNo8gf58MFByDdRzAIrpdBoI50QFB5bcFtz0n3/FP4WaeFAFAjibulGQczCA8VtVEnOr5F6pQbMz9LXYbh4o5dOWB+e4bptVatPU4g6cYNmE9PR4+v/k/IvBirCQs=
