language: java
jdk: oraclejdk11
notifications:
  slack:
    on_success: always
addons:
  sonarcloud:
    organization: "metaxiii"
    token:
      secure: "f2sBQOd5h16EHNzync5GSA2Q3CQl3CCDEv9+3sNBvWowo5qGuchNbk6FEJPppZYfLq96V7gfZ495iKdR+pPcvlLTUTq0Jz47wopVSuS4KyS8KUl5KVLIp6YesC5k8TWmCuamCE5xfxHnbcTycYTUsShg19/nSVnoEMHA8GvuCabd0ID9kUGKHHGd6IwEK/sr5sALtY4Lu0Y5IKF9Lo/xUdDnBqI42n84icCMnlPzVEs8EYVEFlNRRxXmGdZisl
      kxZdKZdHb/YJnJe1OAvbMVEXPk1KdTgN8CxveGJpprIMi0pDwCbDddwSPQuB+nTG4T1i5WKJFuxmnZyVdIvwIbV1AZU6Bqq6ovrNM+zJCV3IOPILYEGa2uO6UwjU9dB6XMgP/COxy77+Yyy+tMaGDVSxA8lcENaL7LVpcEuvt7JsrNOw7DpyjOKtt9NDwQI+/fuqmO2cr23fflV8gxxBOyoosHTCIFJ+T6nHHZDES+sGfK0JavX/KAtB+I/UbVZbIupuyLS4G
      iPNbqVunrsBD1U6PBxWKA5wwQMRxQxPE26UyMRNpRlN4XJ5U6Qfy8TFKWijxPSmGFqaYAr3sfimsIXGGdBxZe6LlKC7LmJXoa89mkf5ZTN10dnGk/Gl5XWuZrZAVGLGBOIql8Yh5lAUVaje+OB1wx5rX5RTZS0ydHzls="
script:
  - mvn clean install org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar -Dsonar.projectKey=metaXIII_OC-java-P10
