language: java
jdk: oraclejdk11
notifications:
  slack:
    on_success: always
addons:
  sonarcloud:
    organization: metaxiii
    token:
      secure: IQcOigNgp/btn0myzeP0/ay6LRa/Cp/muPak9+1/3c59P3fjjNodVSIAH1v3ORmmyAdcPtgWMGTZctfMLUPG1WeF3JttiSlgIzGT+JRH3BjaSztOUq8NI+YFnFOQP25+yy4xhuLFUSa3u9vxxzy2I8gpd7KwNoBFW7jJlwikCBeqSDtklBp9n6kQTO+bJwpl+fzZcRf3UJDLrQF0VDukrt/ofbwEAkR7d7MYj5b6cz3YLxupDG1iKwtHn//zYeKB/Lzb7z4OUOjm3TRFjXM7zQJ0/4nCNHggqE/PXao5liWEh84LAAexLFn9gkkMrAZEan7EtNEF3OpQv2rlixjTb9tGSriRV0Vx3h6HaBT6KraZH1Ku0xhO/XJABoEHiYkobF1r24Shl92C5aTim0mraVYtiO5cUhIswHGU0r1IznOa9Qr8Ol8Vp+MXQ/3c6acIYHW1zYGtahGyJpSyWjWLP50kIIe0byFYrdC/5tnP1DXajlq64xJTdQzhKniUVr6PtvY9iCAInJ4k77NMuWGQf1NcQaR5jeJKfT+83Y7aH3KxqeZVEuom8Al4/wO9EVaQHmfb6eV/XdYfC0u6VqHLLMRtI7ck7GeK/NiIBndsUyQO6RaHZEDTnrRnX6Ja0FVOAin+tnzfiKxgGaYLrEhT6JDVZfjCvfDBXM9vIw8o16c=
script:
- mvn clean install org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar -Dsonar.projectKey=metaXIII_OC-java-P10

